const PREFIX = 'USER'

export const CREATE_USER = `${PREFIX}/CREATE_USER`
export const DELETE_USER = `${PREFIX}/DELETE_USER`
export const SELECT_USER = `${PREFIX}/SELECT_USER`
export const UPDATE_USER = `${PREFIX}/UPDATE_USER`
